services:
  - type: web
    name: extract-pdf-contract
    env: python
    runtime: python@3.11
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker run:app
